### PR TITLE
Fix MID 0002 Implementation

### PR DESCRIPTION
**Pull request by ferm10n**
# context

https://github.com/st-one-io/node-open-protocol/issues/40

### CODE REVIEW

**Comment by ferm10n** [comment]
A PR for this branch was also created in the upstream project, and outlines a few concerns with the changes to the payload and the tests https://github.com/st-one-io/node-open-protocol/pull/41

**Comment by ferm10n** [comment]
The CI job is failing, but so does `develop`. In fact, this branch produces one less failing test than `develop`: *Should close connection, fail send keepAlive by retry and timeout - Based Test 30/08/2018*

**Comment by joshpruett** [comment]
Are you concerned about [this](https://github.com/RV-Argonaut/node-open-protocol/pull/4/checks#step:6:443) error @ferm10n? If not, I think it's fine to approve.

```
  3) Open Protocol Parser
       should emit an error when input is not a buffer:
     TypeError [ERR_INVALID_ARG_TYPE]: The "chunk" argument must be of type string or an instance of Buffer or Uint8Array. Received an instance of Object
      at new NodeError (node:internal/errors:387:5)
      at _write (node:internal/streams/writable:314:13)
      at OpenProtocolParser.Writable.write (node:internal/streams/writable:336:10)
      at Context.<anonymous> (test/openProtocolParser.spec.js:32:16)
      at processImmediate (node:internal/timers:466:21)
```

**Comment by ferm10n** [comment]
> Are you concerned about [this](https://github.com/RV-Argonaut/node-open-protocol/pull/4/checks#step:6:443) error @ferm10n? If not, I think it's fine to approve.
> 
> ```
>   3) Open Protocol Parser
>        should emit an error when input is not a buffer:
>      TypeError [ERR_INVALID_ARG_TYPE]: The "chunk" argument must be of type string or an instance of Buffer or Uint8Array. Received an instance of Object
>       at new NodeError (node:internal/errors:387:5)
>       at _write (node:internal/streams/writable:314:13)
>       at OpenProtocolParser.Writable.write (node:internal/streams/writable:336:10)
>       at Context.<anonymous> (test/openProtocolParser.spec.js:32:16)
>       at processImmediate (node:internal/timers:466:21)
> ```

This was a failing test on [`develop`](https://github.com/RV-Argonaut/node-open-protocol/actions/runs/4545569915/jobs/8013084677#step:6:444) so I think it's fine.

**Review by joshpruett — APPROVED** [review]

**Pull request merged**
